### ISSUE TITLE
Reconsider pros and cons of monorepo

### ISSUE THREAD

**Issue by loboda4450** [kouprlabs/voltaserve#152]
While developing the pipelines, I wondered if there was any way to clean up the mess it contained. I came to the conclusion that breaking each microservice into a separate repository would bring more benefits than problems. With the future in mind, creating issues is rather targeted at a specific microservice rather than the entire project, the same situation is with PRs. I don't really know how public github works, but I'm guessing that rate limits on runners also work differently within an organization than within a single repository. The issues of environment variables or secrets can be omitted, because they can be set for the entire organization, the same will happen with pipelines, create generic ones in a separate repository and only call them from a specific one.

Let's have a discussion 😄

**Comment by dsonck92** [comment]
Well, I for one think this is nice, because, if we just toy with the idea I already have of utilizing the "api" as library, then this also allows other services to build against the client for a specific version.

So, just imagine, we move the `webdav/client/api_client.go` over to `api/client.go`, then all the projects can depend on `github.com/kouprlabs/voltaserve-api/v2@2.0.1` and utilize `api.Client`. Then if we are strict with the API versioning (which we probably should if we're going to get rclone involed with this), then external services can be freely updated without dependents to migrate.

It would also be nice (Kubernetes native) if the clients check for the version they require and the version the API has, so it can "unready" itself while this isn't true (this makes it possible to do a rollout release of the API, which requires a new Mosaic, stays unready, and later Mosaic gets that rollout release, unblocking the API, getting to the new API server with 0 downtime)

**Comment by dsonck92** [comment]
Now, as we're talking about repo migrations, I also quickly want to plug gitlab into the mix. I'm personally not too fond of Github, and their lack of hierarchy as well. Of course this is entirely up to @bouassaba because just migrating over an organization is a *big* thing, however it might bring some neat features back among which:
- integrated docker registry. Though we should still mirror to dockerhub for convenience
- better CI integration into the MRs, and (in my opinion) more flexible pipelines
- and more interesting issue tracking
But well, this, again, is a big change, so I don't want to impose this change. I'm really fine either way, but now we're still fresh~

**Comment by bouassaba** [comment]
These are definitely valuable ideas that you guys are bringing, I also had to go through this important decision sometime ago, me having worked with "separate repos for each microservice" nearly entire my life, with other companies as well, I settled with a the idea of monorepo for Voltaserve for many reasons, some of them are:
1) separate repos bring a big overhead in maintenance, just look how at how Sony and Apple decided to use FreeBSD over a Linux distro, just mainly because the whole codebase is easy to maintain and integrate being one repo. It ensures the product integrates well as a "whole".
2) Vercel (which is the new fresh cool tech company in town) just bought a startup that specializes in monorepos (https://turbo.build/)
3) Google is having their entire stack in a monorepo.
4) With one repo, it's easy to increase the visibility of the project in the world, easy to share etc, that's very important for open source projects (unlike corporate stuff)

So, I would say, let us stick with the monorepo, I'm pretty sure it will bring us more benefits than harm in the long run.
And thank you guys for the suggestions, it's really awesome to read through these discussions! 🔥

**Comment by loboda4450** [comment]
> Now, as we're talking about repo migrations, I also quickly want to plug gitlab into the mix. I'm personally not too fond of Github, and their lack of hierarchy as well. Of course this is entirely up to @bouassaba because just migrating over an organization is a _big_ thing, however it might bring some neat features back among which:
> 
>     * integrated docker registry. Though we should still mirror to dockerhub for convenience
> 
>     * better CI integration into the MRs, and (in my opinion) more flexible pipelines
> 
>     * and more interesting issue tracking
>       But well, this, again, is a big change, so I don't want to impose this change. I'm really fine either way, but now we're still fresh~
> 
> 
> EDIT: Oh yes, and of course the best thing about it is, it's theoretically possible to self host. And requesting additional CI hours is possible if we adhere to a proper Open Source license and request to be part of their Ultimate for Open Source deal, which I'm using at my self hosted variant.

Ad 1. Github also has its own container registry, we should consider pushing images there too @bouassaba 
Ad 2. Definetly agree, I have selfhosted gitlab on my own too :)
Ad 3. Maybe there is a way to have an enterprise license on this project on GitHub too.

About the edit. This project needs the audience, and as I can recall Gitlab is not the first place when you are going to find any awesome-selfhosted. What's more, Github CI's are way better than Gitlab ones, I'd say they are the best in the market. I think we just didnt reach the end of CI integration :)
